name: flutter_keypad_example
description: A nostalgic keypad example
publish_to: 'none'

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
